steps:
  # Build the container image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${_NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/mapiker-frontend:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/mapiker-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mapiker-frontend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/mapiker-frontend:latest'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/mapiker-frontend:latest'

substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: ''
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''
  _NEXT_PUBLIC_API_URL: ''
  _NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ''
  _NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ''

options:
  logging: CLOUD_LOGGING_ONLY
